### PR TITLE
Deleting un-used code in default files

### PR DESCRIPTION
**Pull request by Mike-Loffland**

### CODE REVIEW

**Comment by deewuok** [comment]
hi All

I thought gulp was being taken out?

**Comment by Mike-Loffland** [comment]
Dee... You are correct.

I was going to address that stuff in a different PR... But, it probably makes more sense to wrap all the cleanup stuff into one PR.

**Comment by deewuok** [comment]
Hi Mike

Great…. I think we are making great progress and thanks for all the stuff you put in.  BTW what’s PR?

**Comment by Mike-Loffland** [comment]
PR = Pull Request

**Pull request closed without merging**
