### PR TITLE
Using Angular Leaflet Directive's native autoDiscover to get current position

### PR DESCRIPTION
**Pull request by Mike-Loffland**
I'm a newbie to pull requests... so let me have it if I did something wrong.

### CODE REVIEW

**Comment by Mike-Loffland** [comment]
I meant to wrap app.js in an IIFE before I pushed.

**Comment by joekarl** [comment]
Great job @Mike-Loffland! 
I'm diggin the leaflet angular directive. 

I'm unsure about using the autoDiscover feature exposed in there though. The leaflet-angular-directive code doesn't really give any good options for handling location lookup failures (https://github.com/tombatossals/angular-leaflet-directive/blob/a40fe62605f08d10c9c2a9b8131cc30c5b8f48d6/src/directives/center.js#L172-L180) and makes some questionable decisions about defaults for finding the user's location (https://github.com/tombatossals/angular-leaflet-directive/blob/a40fe62605f08d10c9c2a9b8131cc30c5b8f48d6/src/directives/center.js#L115-L125). 
In particular, on failure there's just a log warning made with no chance to intercept or give user feedback, and on locate you can't set things like timeout or setting high/low accuracy. 

Also it couples the map's center to finding the user's location which will become a problem if we want to lookup the user's location without centering the map on it (ie if we're centering the map around a set of filtered points).

I'm definitely liking the use of the leaflet directive but I'd think we'd want to lean toward handling the user's location separately. 

Thoughts? 
//cc @jvrousseau

**Comment by Mike-Loffland** [comment]
@joekarl Excellent points... Coupling the map's center with the user location in particular.

A custom geolocation-centric service/directive would definitely allow for more control.

**Comment by Mike-Loffland** [comment]
Geolocation factory: https://github.com/ninjatronic/ngGeolocation/blob/master/ngGeolocation.js

Returns a promise... Looks like it could fit the bill.

**Comment by DevinClark** [comment]
:+1:

**Comment by joekarl** [comment]
+1 
I like this better than what I had in #19.
If it's cool, make a new PR with the leaflet-angular-directive and the geolocation factory and we'll get it merged in. Feel free to rip out the current location service file as the geolocation factory looks to be a better option.

**Comment by Mike-Loffland** [comment]
Will do... Does anybody foresee a usage scenario for the watchPosition method within the School Finder app?

**Comment by joekarl** [comment]
Not right now, people are probably stationary when they use the app.

**Pull request merged**
