### PR TITLE
Make map use angular leaflet directive

### LINKED ISSUE #35: Move map generation into a service
Need to have the map generation moved into an angular service/factory (not sure which) so it can be injected into the main controller for manipulation based on $scope changes.

### PR DESCRIPTION
**Pull request by joekarl**
Add menu bar (for testing, will be ripped out later I assume)
Hook in current location service
Move css into separate file

fixes #35

### CODE REVIEW

**Comment by joekarl** [comment]
@DevinClark this look about right to you?

**Comment by DevinClark** [comment]
@joekarl looks good to me

**Comment by joekarl** [comment]
So I'm conflicted here. I don't know whether the way I'm doing the async button thing is the best way of doing things.
Essentially what's happening is on button click, the directive calls a function out of the controller scope and then waits for said function to complete.
This seems smelly.
I would think the other alternative is to have the directive call the actual service function I want to call and then either update the scope directly, or $emit an event saying that the current location changed.

Thoughts?

**Comment by joekarl** [comment]
Closing because of #41

**Pull request closed without merging**
