### PR TITLE
Add current location service

### LINKED ISSUE #19: Get Current Location

### PR DESCRIPTION
**Pull request by joekarl**
Add css/script folders
Add sample for hooking into current location service
Add gulp serve to run a local webserver

Fixes #19

### CODE REVIEW

**Comment by joekarl** [comment]
I'm in favor of using bower but there was some concern from @jvrousseau and @DevinClark about introducing another dependency/build tool. 

As for the symlink thing, I honestly forgot that was a problem :smile:. We probably need to move the npm module stuff inside off the app folder or use bower or something to transplant those files directly inside of the app/scripts folder.

**Comment by joekarl** [comment]
@DevinClark @jvrousseau is this code ridiculous? In particular, the service definition and the sample in tests->geolocation->index.html (I does not know how to angular...)

**Comment by mkchandler** [comment]
Considering we have (and will have) a wide variety of devs working with us, I think it's best to make sure we support someone running msysgit. That being said, I'm not familiar with the exact issue discussed in here.

**Comment by Mike-Loffland** [comment]
I'm not familiar with the issue either... Is it because of the global flag when you're installing a module via NPM?

**Comment by joekarl** [comment]
It was because I symlinked the angular js/css from the node_modules folder
to the css/scripts. For now I just copied them over but we'll have to think
about a better long term solution (hint hint bower).

Karl

Sent from my iPhone

On Jan 28, 2015, at 7:49 PM, Mike Loffland <notifications@github.com> wrote:

I'm not familiar with the issue either... Is it because of the global flag
when you're installing a module via NPM?

—
Reply to this email directly or view it on GitHub
<https://github.com/codeforokc/school-finder/pull/33#issuecomment-71954748>.

**Comment by mkchandler** [comment]
I'm cool with Bower if that's what will work best :+1:

**Comment by DevinClark** [comment]
Just reference the files from the node modules directory in dev then use a concat task for prod. This is exactly what you would be doing with bower, correct?

**Comment by joekarl** [comment]
@DevinClark yeah, that's what I had before but was running into issues with trying to use the gulp-serve plugin for spinning up a quick server (for phone testing and the like). As of right now it's not an issue because there's no build pipeline, so with the symlinks gone we'll make a better long term solution later.

**Comment by Mike-Loffland** [comment]
I'm not familiar with symbolic links... What commit did you do the symbolic link? Is it a Unix deal?

**Comment by joekarl** [comment]
@Mike-Loffland got introduced here https://github.com/codeforokc/school-finder/commit/f44028f487e427462daef433b6b23b359aab3bc4

Essentially in *nix you can create a link that acts like a file or a folder but really is just a pointer in the filesystem to an underlying file/folder. There's equivalents in windows as well, but there's translation issues between the two. Here's the tl;dr http://en.wikipedia.org/wiki/Symbolic_link#POSIX_and_Unix-like_operating_systems

**Comment by Mike-Loffland** [comment]
:+1:

**Pull request merged**
